name: flutter_oewa
description: A flutter package wrapper around the OEWA Android and iOS SDKs.
version: 1.0.1
homepage: https://github.com/marqably/flutter_oewa

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.marqably.flutter_oewa
        pluginClass: FlutterOewaPlugin
      ios:
        pluginClass: FlutterOewaPlugin